FROM amd64/ubuntu:latest

# Update Sources
RUN apt update

# PreReqs
RUN apt install curl -y
RUN apt install python3-pip -y
RUN apt install -y gnupg wget apt-transport-https software-properties-common
RUN apt install sudo unzip -y
RUN apt install nano -y
RUN apt install locales -y
RUN locale-gen en_US.UTF-8
RUN sudo apt install libluajit-5.1-dev -y
RUN sudo apt install cmake -y
RUN sudo apt install ninja-build -y

# Checkov
RUN pip3 install checkov -q
RUN pip3 install -U checkov

# Powershell
RUN wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
RUN dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb
RUN apt update 
RUN apt install powershell -y

# Terraform
RUN wget -O- https://apt.releases.hashicorp.com/gpg | \
	gpg --dearmor | \
	tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
	https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
	tee /etc/apt/sources.list.d/hashicorp.list
RUN apt update
RUN apt install terraform terraform-ls -y
RUN curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

# AZCLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# NeoVim
RUN add-apt-repository ppa:neovim-ppa/unstable -y
RUN apt update -y
RUN apt install neovim -y

# Dotfiles

# PS Modules
RUN pwsh -command Install-Module -Name Az -Scope AllUsers -AcceptLicense -SkipPublisherCheck -Force
RUN pwsh -command Install-Module -Name posh-git -Scope AllUsers -AcceptLicense -SkipPublisherCheck -Force
